(local love (require :love))

;; (local (h w) (love.window.getMode))
(local default-height 720)
(local size (/ 1 8))
(import-macros {: log} :macro)

(log [:available-canvases (love.graphics.getCanvasFormats)])
(local hover-canvas (love.graphics.newCanvas 160 90 {:format :rgba16f}))
;; RGB565, RGB5a1,RGB16f,RGB4, SRGB8,Stencil8
(local unit-shader (love.graphics.newShader :assets/shaders/unit.glsl))

(var unit_id 0)
(var feature_id 0)
(var r 0)
(var g 0)
(var _b 0)
(var _a 0)

(fn update [objects default-ret]
  (local lg love.graphics)
  (lg.push :all)
  (local state (require :src.state))
  (lg.reset)
  (lg.setCanvas hover-canvas)
  (lg.clear 0 0 0 0)
  (lg.setColor 1 1 1 1)
  (lg.scale state.camera.scale)
  ;; (lg.translate (- state.camera.x)  (- state.camera.y))
  (local (_ height) (love.window.getMode))
  (local ratio (/ height default-height))
  (lg.scale (/ size ratio))
  (lg.translate state.camera.x state.camera.y)
  (lg.setShader unit-shader)
  ;; (lg.scale 0.5)
  ;; (local max 256)
  ;;(unit-shader:send :id_max max)
  (each [key obj (ipairs objects)]
    (unit-shader:send :unit_id (if (= obj.type :unit)
                                   ;;(/ obj.id max)
                                   obj.id
                                   0))
    (unit-shader:send :feature_id (if (= obj.type :feature)
                                      ;;(/ obj.id max)
                                      obj.id
                                      0))
    (obj:draw))
  (lg.setCanvas)
  (lg.pop)
  
  (local (mx my) (love.mouse.getPosition))
  (local hover-canvas-data (hover-canvas:newImageData))
  ;; readPixels: Format and type RGBA/UNSIGNED_SHORT_4_4_4_4 incompatible with this RGBA4 attachment. This framebuffer requires either RGBA/UNSIGNED_BYTE or getParameter(IMPLEMENTATION_COLOR_READ_FORMAT/_TYPE) RGBA/UNSIGNED_BYTE.
  (local (lcr lcg lc_b lc_a) (hover-canvas-data:getPixel (math.floor (/ mx (/ 1 size) ratio)) (math.floor (/ my (/ 1 size) ratio))))
  ;; (pp [lcr lcg lc_b lc_a])size
  (set r lcr)
  (set g lcg)
  (set _b lc_b)
  (set _a lc_a)
  (hover-canvas-data:release)
  (set unit_id (math.floor (* 1 r)))
  (set feature_id (math.floor (* 1 g)))
  (accumulate [ret default-ret _ un (ipairs objects)] (if (or (and (= un.type :unit) (= unit_id un.id))
                                                              (and (= un.type :feature) (= feature_id un.id)))
                                                          un ret))
          
)

(fn draw [objects focus? editor?]
  (local lg love.graphics)
  (var hover false)
  (var outline-callback false)
  (local params (require :src.params))
  (when (and _G.dev params.debug-view)
    (lg.push)
    (lg.reset)
    (local (_ height) (love.window.getMode))
    (local ratio (/ height default-height))
    (lg.print unit_id 200 10)
    (lg.print feature_id 200 30)
    (lg.print (string.format "r:%s, g:%s, b:%s, a:%s" r g _b _a) 200 50)
    (lg.scale (* 8 ratio))
    (lg.draw hover-canvas)
    (lg.pop)
    )
  (lg.setColor 1 1 1 1)
  (lg.push :all)
  ;; (lg.scale 4)  
  (lg.setColor 1 1 1 1)
  (local {: hexgrid : player-team} (require :src.state))
  (each [k obj (ipairs objects)]
    (let [d (hexgrid.grid:get obj.i obj.j)
          {: visible : visited} d
          can-see (or editor? (. visible player-team))
          has-seen (or editor? (. visited player-team))]
      (when (and focus? can-see (= obj.type :unit) (= unit_id obj.id))
        (set hover obj)
        (set outline-callback (fn [] (obj:outline))))
      (when (and focus? has-seen (= obj.type :feature) (= feature_id obj.id))
        (set hover obj)
        (set outline-callback (fn [] (obj:outline))))))
  (lg.pop)
  (values outline-callback
          (fn [] (each [_ obj (ipairs objects)]
                   (when (~= obj hover)
                     (let [d (hexgrid.grid:get obj.i obj.j)
                           {: visible : visited} d
                           can-see (. visible player-team)
                           has-seen (. visited player-team)]
                       (if (or (and (= obj.type :unit) can-see) editor?)
                           (obj:draw)
                           (or (and (= obj.type :feature) can-see) editor?)
                           (do
                             (lg.push)
                             (lg.reset) ;; sloooow
                             (local {: fonts} (require :src.resources))
                             (local {: names} (require :src.feature-names))
                             (lg.setFont fonts.text)
                             (local {: camera} (require :src.state))
                             (local {:x cx :y cy :scale cs} camera)
                             (local message (. names obj.name))
                             (local w (fonts.text:getWidth message))
                             (local h (fonts.text:getHeight message))
                             (local padding 10)
                             (local wp (+ (* 2 padding) w))
                             (local tw 32)
                             (lg.translate (math.floor (/ (- (* cs tw) wp) 2)) 0)
                             (lg.translate (* cs cx) (* cs cy))
                             (lg.setColor 0 0 0 1)
                             (lg.setLineWidth 8)
                             (lg.rectangle :line (* cs obj.x) (- (* cs obj.y) 6) (+ (* 2 padding) w) (+ (* 2 padding) h))
                             (lg.setColor 1 1 1 1)
                             (lg.rectangle :fill (* cs obj.x) (- (* cs obj.y) 6) (+ (* 2 padding) w) (+ (* 2 padding) h))
                             (lg.setColor 0 0 0 1)
                             (lg.print message (+ padding (* cs obj.x)) (+ padding (- (* cs obj.y) 6)))                             
                             (lg.setColor 1 1 1 1)
                             (lg.pop)
                             (obj:draw))
                           (and (= obj.type :feature) has-seen)
                           (do
                             (lg.push :all)
                             (lg.setColor 1 1 1 0.5)
                             (obj:draw)
                             (lg.pop)
                             )
                           )))))
          hover hover-canvas)
  )


{: draw : update}
